const express = require('express');
const jwt = require('jsonwebtoken');
const multer = require('multer');
const path = require('path');
const User = require('../models/User');
const Song = require('../models/Song');
const Mix = require('../models/Mix');
const Artist = require('../models/Artist');
const Playlist = require('../models/Playlist');
const { sendPasswordResetEmail, sendWelcomeEmail } = require('../config/email');
const { protect } = require('../middleware/auth');
const router = express.Router();

const generateToken = (id) => {
    return jwt.sign({ id }, process.env.JWT_SECRET || 'wave_secret_key_2024', { expiresIn: '30d' });
};

const avatarStorage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, 'uploads/covers/'),
  filename: (req, file, cb) => cb(null, 'avatar-' + Date.now() + path.extname(file.originalname))
});
const avatarUpload = multer({ storage: avatarStorage });

async function createWaveMix(userId, preferences) {
    try {
        const artists = await Artist.find({ _id: { $in: preferences } });
        const artistNames = artists.map(a => a.name);
        let songs = await Song.find({ artist: { $in: artistNames }, isPublic: true });
        let mixes = await Mix.find({ artist: { $in: artistNames } });
        songs = [...songs, ...mixes];
        if (songs.length < 25) {
            const moreSongs = await Song.find({ artist: { $nin: artistNames }, isPublic: true, _id: { $nin: songs.map(s => s._id) } }).sort({ plays: -1 }).limit(25 - songs.length);
            songs = [...songs, ...moreSongs];
        }
        songs = songs.slice(0, 25);
        if (songs.length > 0) {
            await Playlist.create({ name: 'My Wave Mix 🌊', description: 'Your weekly personalized mix', user: userId, songs: songs.map(s => s._id), isAutoGenerated: true, lastUpdated: new Date() });
        }
    } catch(e) { console.error('Wave Mix creation error:', e.message); }
}

// REGISTER
router.post('/register', async (req, res) => {
    try {
        const { username, email, password, preferences } = req.body;
        const userExists = await User.findOne({ email });
        if (userExists) return res.status(400).json({ error: 'User already exists' });
        const userCount = await User.countDocuments();
        const role = userCount === 0 ? 'superadmin' : 'user';
        const user = await User.create({ username, email, password, role });
        if (preferences && preferences.length > 0) { await createWaveMix(user._id, preferences); }
        try { await sendWelcomeEmail(email, username); } catch (e) {}
        res.status(201).json({ token: generateToken(user._id), user: { id: user._id, username: user.username, email: user.email, role: user.role, avatar: user.avatar, bio: user.bio } });
    } catch (error) { res.status(500).json({ error: 'Server error' }); }
});

// LOGIN
router.post('/login', async (req, res) => {
    try {
        const { email, password } = req.body;
        const user = await User.findOne({ email });
        if (!user) return res.status(401).json({ error: 'Invalid credentials' });
        const isMatch = await user.matchPassword(password);
        if (!isMatch) return res.status(401).json({ error: 'Invalid credentials' });
        res.json({ token: generateToken(user._id), user: { id: user._id, username: user.username, email: user.email, role: user.role, avatar: user.avatar, bio: user.bio } });
    } catch (error) { res.status(500).json({ error: 'Server error' }); }
});

// FORGOT PASSWORD
router.post('/forgot-password', async (req, res) => {
    try {
        const { email } = req.body;
        const user = await User.findOne({ email });
        if (!user) return res.status(404).json({ error: 'No account' });
        const resetToken = jwt.sign({ id: user._id }, process.env.JWT_SECRET || 'wave_secret_key_2024', { expiresIn: '1h' });
        const resetLink = `http://localhost:5000/reset-password.html?token=${resetToken}`;
        try { await sendPasswordResetEmail(email, resetLink); } catch (e) { console.log('Reset link:', resetLink); }
        res.json({ message: 'Reset link sent!' });
    } catch (error) { res.status(500).json({ error: 'Server error' }); }
});

// RESET PASSWORD
router.post('/reset-password/:token', async (req, res) => {
    try {
        const { password } = req.body;
        const decoded = jwt.verify(req.params.token, process.env.JWT_SECRET || 'wave_secret_key_2024');
        const user = await User.findById(decoded.id);
        if (!user) return res.status(404).json({ error: 'User not found' });
        user.password = password;
        await user.save();
        res.json({ message: 'Password reset!' });
    } catch (error) { res.status(400).json({ error: 'Invalid or expired token' }); }
});

// GET PROFILE
router.get('/profile', protect, async (req, res) => {
    try { const user = await User.findById(req.userId).select('-password'); res.json(user); }
    catch (error) { res.status(500).json({ error: 'Server error' }); }
});

// UPDATE PROFILE
router.put('/profile', protect, avatarUpload.single('avatar'), async (req, res) => {
    try {
        const user = await User.findById(req.userId);
        if (!user) return res.status(404).json({ error: 'User not found' });
        const { username, email, bio } = req.body;
        if (username) user.username = username;
        if (email) user.email = email;
        if (bio) user.bio = bio;
        if (req.file) user.avatar = `/uploads/covers/${req.file.filename}`;
        await user.save();
        res.json({ message: 'Profile updated!', user: { id: user._id, username: user.username, email: user.email, avatar: user.avatar, bio: user.bio, role: user.role } });
    } catch (error) { res.status(500).json({ error: 'Update failed' }); }
});

// GET ARTISTS (from users who have uploaded)
router.get('/artists', async (req, res) => {
    try {
        const songs = await Song.find({ isPublic: true });
        const artistIds = [...new Set(songs.map(s => s.uploadedBy?.toString()).filter(Boolean))];
        const artists = await User.find({ _id: { $in: artistIds } }).select('username avatar bio');
        res.json(artists);
    } catch (error) { res.json([]); }
});

// UPDATE MY WAVE MIX
router.post('/update-wave-mix', protect, async (req, res) => {
    try {
        const playlist = await Playlist.findOne({ user: req.userId, name: 'My Wave Mix 🌊' });
        if (!playlist) return res.status(404).json({ error: 'Playlist not found' });
        const preferences = req.body.preferences || [];
        const artists = await Artist.find({ _id: { $in: preferences } });
        const artistNames = artists.map(a => a.name);
        let songs = await Song.find({ artist: { $in: artistNames }, isPublic: true });
        let mixes = await Mix.find({ artist: { $in: artistNames } });
        songs = [...songs, ...mixes];
        if (songs.length < 25) {
            const moreSongs = await Song.find({ artist: { $nin: artistNames }, isPublic: true, _id: { $nin: songs.map(s => s._id) } }).sort({ plays: -1 }).limit(25 - songs.length);
            songs = [...songs, ...moreSongs];
        }
        songs = songs.slice(0, 25);
        playlist.songs = songs.map(s => s._id);
        playlist.lastUpdated = new Date();
        await playlist.save();
        res.json({ message: 'Wave Mix updated!', playlist });
    } catch (error) { res.status(500).json({ error: 'Update failed' }); }
});

module.exports = router;