const express = require('express');
const router = express.Router();
const Playlist = require('../models/Playlist');
const Song = require('../models/Song');
const { protect } = require('../middleware/auth');

// Get or generate weekly wave playlist for user
router.get('/weekly-wave', protect, async (req, res) => {
    try {
        const currentWeek = getWeekNumber();
        const year = new Date().getFullYear();
        
        let weeklyPlaylist = await Playlist.findOne({
            user: req.userId,
            name: `Weekly Wave ${year} - Week ${currentWeek}`,
            isAutoGenerated: true
        });
        
        if (!weeklyPlaylist) {
            const songs = await generateWeeklySongs();
            
            weeklyPlaylist = await Playlist.create({
                name: `Weekly Wave ${year} - Week ${currentWeek}`,
                description: `Fresh picks for week ${currentWeek} of ${year}. Different artists every week.`,
                user: req.userId,
                songs: songs.map(s => s._id),
                isAutoGenerated: true,
                lastUpdated: new Date()
            });
        }
        
        await weeklyPlaylist.populate('songs');
        res.json(weeklyPlaylist);
    } catch (error) {
        res.status(500).json({ error: 'Failed to get weekly wave' });
    }
});

// Get all past weekly waves
router.get('/weekly-wave/past', protect, async (req, res) => {
    try {
        const playlists = await Playlist.find({
            user: req.userId,
            name: { $regex: /Weekly Wave/, $options: 'i' },
            isAutoGenerated: true
        }).sort({ createdAt: -1 }).limit(10);
        
        res.json(playlists);
    } catch (error) {
        res.json([]);
    }
});

// Get single playlist by ID
router.get('/:id', protect, async (req, res) => {
    try {
        const playlist = await Playlist.findById(req.params.id).populate('songs');
        if (!playlist) return res.status(404).json({ error: 'Not found' });
        res.json(playlist);
    } catch (error) {
        res.status(500).json({ error: 'Failed to load' });
    }
});

function getWeekNumber() {
    const now = new Date();
    const start = new Date(now.getFullYear(), 0, 1);
    const days = Math.floor((now - start) / (24 * 60 * 60 * 1000));
    return Math.ceil((days + start.getDay() + 1) / 7);
}

async function generateWeeklySongs() {
    const allSongs = await Song.find({ isPublic: true }).sort({ createdAt: -1 });
    
    if (allSongs.length === 0) return [];
    
    const songsByArtist = {};
    allSongs.forEach(song => {
        if (!songsByArtist[song.artist]) {
            songsByArtist[song.artist] = [];
        }
        songsByArtist[song.artist].push(song);
    });
    
    const artistNames = Object.keys(songsByArtist);
    const shuffledArtists = shuffleArray([...artistNames]);
    const selectedArtists = shuffledArtists.slice(0, 20);
    
    const weeklySongs = [];
    for (const artist of selectedArtists) {
        const artistSongs = songsByArtist[artist];
        const randomSong = artistSongs[Math.floor(Math.random() * artistSongs.length)];
        weeklySongs.push(randomSong);
    }
    
    return weeklySongs;
}

function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

module.exports = router;